sudo: required

language: ruby

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

install:
 - docker-compose up -d

script:
 - docker-compose run -e RAILS_ENV=test lemonade_stand_web rake db:create
 - docker-compose run -e RAILS_ENV=test lemonade_stand_web rake db:migrate
 - docker-compose run -e RAILS_ENV=test lemonade_stand_web rake test

