lemonade_stand_web:
  build: .
  ports:
    - "3000"
  links:
    - lemonade_stand_db
lemonade_stand_db:
  image: library/mysql:latest
  ports:
    - "3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

